name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-build:
    runs-on: windows-latest

    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_HOST: ${{ secrets.DBT_HOST }}
      DBT_PORT: 5432
      DBT_DBNAME: ${{ secrets.DBT_DBNAME }}
      DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
      DBT_TARGET: dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dbt
        run: |
          pip install dbt-postgres

      - name: Create profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "
          hellochef_dbt:
            target: dev
            outputs:
              dev:
                type: postgres
                host: ${DBT_HOST}
                user: ${DBT_USER}
                password: ${DBT_PASSWORD}
                port: 5432
                dbname: ${DBT_DBNAME}
                schema: ${DBT_SCHEMA}
                threads: 4
          " > ~/.dbt/profiles.yml

      - name: Check if DBT secrets are empty
        run: |
          if [ -z "$DBT_USER" ]; then echo "DBT_USER is empty"; else echo "DBT_USER is set"; fi
          if [ -z "$DBT_PASSWORD" ]; then echo "DBT_PASSWORD is empty"; else echo "DBT_PASSWORD is set"; fi
          if [ -z "$DBT_HOST" ]; then echo "DBT_HOST is empty"; else echo "DBT_HOST is set"; fi
          if [ -z "$DBT_PORT" ]; then echo "DBT_PORT is empty"; else echo "DBT_PORT is set"; fi
          if [ -z "$DBT_DBNAME" ]; then echo "DBT_DBNAME is empty"; else echo "DBT_DBNAME is set"; fi
          if [ -z "$DBT_SCHEMA" ]; then echo "DBT_SCHEMA is empty"; else echo "DBT_SCHEMA is set"; fi
          if [ -z "$DBT_TARGET" ]; then echo "DBT_TARGET is empty"; else echo "DBT_TARGET is set"; fi

      - name: Run dbt deps
        run: dbt deps

      - name: Run dbt build
        run: dbt build
