name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt-build:
    runs-on: windows-latest

    env:
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_HOST: ${{ secrets.DBT_HOST }}
      DBT_PORT: "5432"
      DBT_DBNAME: ${{ secrets.DBT_DBNAME }}
      DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
      DBT_TARGET: dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dbt
        run: pip install dbt-postgres

      - name: Create profiles.yml
        shell: pwsh
        run: |
          $content = @"
hellochef_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: '$env:DBT_HOST'
      user: '$env:DBT_USER'
      password: '$env:DBT_PASSWORD'
      port: 5432
      dbname: '$env:DBT_DBNAME'
      schema: '$env:DBT_SCHEMA'
      threads: 4
"@
  New-Item -ItemType Directory -Force -Path $env:USERPROFILE\.dbt
  $content | Out-File -FilePath $env:USERPROFILE\.dbt\profiles.yml -Encoding utf8

      - name: Print profiles.yml (debug)
        shell: pwsh
        run: Get-Content $env:USERPROFILE\.dbt\profiles.yml

      - name: Check DBT secrets
        shell: pwsh
        run: |
          "DBT_USER: $env:DBT_USER"
          "DBT_PASSWORD: $env:DBT_PASSWORD"
          "DBT_HOST: $env:DBT_HOST"
          "DBT_PORT: $env:DBT_PORT"
          "DBT_DBNAME: $env:DBT_DBNAME"
          "DBT_SCHEMA: $env:DBT_SCHEMA"
          "DBT_TARGET: $env:DBT_TARGET"

      - name: Run dbt deps
        run: dbt deps

      - name: Run dbt build
        run: dbt build
